server:
  port: 8090
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # activiti配置
  activiti:
    #校验流程文件，自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
    #表示启动时检查数据库表，不存在则创建
    database-schema-update: true
    #表示哪种情况下使用历史表，这里配置为full表示全部记录历史，方便绘制流程图
    #记录历史等级 可配置的历史级别有none, activity, audit, full
    history-level: full
    #true表示使用历史表
    db-history-used: true
    # 关闭 SpringAutoDeployment
    deployment-mode: never-fail
    # 是否使用uuid，false 不使用/ 默认是 true 使用
    use-strong-uuids: false



